idf_component_register(
    SRCS
        "app_main.c"
        "ble_scanner.c"
        "device_key.c"
        "device_tracker.c"
        "enrollment_mgr.c"
        "proximity_engine.c"
        "vl6180x.c"
        "web_console.c"
    INCLUDE_DIRS "."
    REQUIRES
        bt
        driver
        esp_driver_gpio
        esp_event
        esp_netif
        esp_wifi
        esp_http_server
        nvs_flash
        json
        mbedtls
)
