name: doorlink
description: DoorLink smart entry cross-platform application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Dependency for native OS Share Sheet integration
  share_plus: ^13.1.0 
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.0

flutter:
  uses-material-design: true